### ISSUE TITLE
Workflows should be updated (<yarn graph> and <yarn score> are no longer supported)

### ISSUE THREAD

**Issue by pablomendezroyo** [sourcecred/template-instance#25]
Hey, since you have removed the command `yarn graph` from the **package.json**, should not you **update the github workflows** files? Im having fails in the workflows now  and I gess is because of that.

The new error since the last update appeared is: 
![Screenshot from 2020-11-09 08-14-45](https://user-images.githubusercontent.com/41727368/98510702-d96f7880-2263-11eb-8ddd-aa673e69f2b0.png)

In the package.json the scripts "graph" and "score" are no longer supported:
![Screenshot from 2020-11-09 08-18-09](https://user-images.githubusercontent.com/41727368/98510857-22273180-2264-11eb-89d4-3d2a93fdb3dc.png)

These scripts (`yarn graph` and `yarn score`) are still been used by the workflows:
![Screenshot from 2020-11-09 08-19-30](https://user-images.githubusercontent.com/41727368/98511016-661a3680-2264-11eb-8f4c-7edbb0337949.png)

**Comment by topocount** [comment]
Thanks for logging this @pablomendezroyo ! This was resolved in #22

**Comment by pablomendezroyo** [comment]
> Thanks for logging this @pablomendezroyo ! This was resolved in #22

I may be wrong but, when I run the template since the last release it crashes saying that `yarn graph` does not exists. 

Effectively If I check the workflows, the commands `yarn score` and `yarn graph `are still being used, while they are not longer contemplated in the package json.

**Comment by topocount** [comment]
Apologies @pablomendezroyo ! Thanks for pushing back on this.
