### ISSUE TITLE
"ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by dahifi** [sourcecred/template-instance#92]
Running `yarn install` results in 
```
error https://registry.yarnpkg.com/sourcecred/-/sourcecred-0.9.3.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENAMETOOLONG: name too long, open '/home/el/.cache/yarn/v6/npm-sourcecred-0.9.3-102177228d72be3275df2e381f61516ff1483048-integrity/node_modules/sourcecred/src/plugins/wip-discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvY2hhbm5lbHMvNjc4Mzk0NDA2NTA3OTA1MTI5L21lc3NhZ2VzLzY3ODM5NDQzNjc1NzA5NDQxMC9yZWFjdGlvbnMvc291cmNlY3JlZDo2NzgzOTkzNjQ0MTg1MDI2Njk_YWZ0ZXI9MCZsaW1pdD01'"
```
Tried bumping to 0.10.0 and still fails.

**Comment by hozzjss** [comment]
could you check this https://stackoverflow.com/questions/54741533/nodejs-enametoolong-how-long-is-too-long

**Comment by dahifi** [comment]
Ok, yea, it's 255 on most file systems, but this is in the published sourcecred dependency so how am I supposed to do something about it? Looks like these Discord snapshots shouldn't even be in the yarn package anyways.
